<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
  </ItemGroup>
<ItemGroup>
    <ProjectReference Include="../Skillforge.Databases/Skillforge.Data/Skillforge.Data.csproj" />
    <ProjectReference Include="../Skillforge.Databases/Skillforge.Domain/Skillforge.Domain.csproj" />
  </ItemGroup>
<ItemGroup>
  <Folder Include="Repository\" />
  <Folder Include="Service\" />
  <Folder Include="Utility\" />
  <Folder Include="Controller\" />
</ItemGroup>
</Project>
